const USER ={
  LOGIN: 'USER_LOGIN',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAIL: 'USER_LOGIN_FAIL',
  LOGOUT: 'USER_LOGOUT',
  LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
  LOGOUT_FAIL: 'USER_LOGOUT_FAIL',
}

const ITEMS = {
  LOAD: 'ITEMS_LOAD',
  LOAD_SUCCESS: 'ITEMS_LOAD_SUCCESS',
  LOAD_FAILURE: 'ITEMS_LOAD_FAILURE',
  ADD: 'ITEMS_ADD',
  ADD_SUCCESS: 'ITEMS_ADD_SUCCESS',
  ADD_FAILURE: 'ITEMS_ADD_FAILURE',
  DELETE: 'ITEMS_DELETE',
  DELETE_SUCCESS: 'ITEMS_DELETE_SUCCESS',
  DELETE_FAILURE: 'ITEMS_DELETE_FAILURE',
}

const COMMON = {
  ERROR: 'SET_ERROR'
}
export { USER, ITEMS, COMMON };