const USER ={
  LOGIN: 'USER_LOGIN',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAIL: 'USER_LOGIN_FAIL',
  LOGOUT: 'USER_LOGOUT',
  LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
  LOGOUT_FAIL: 'USER_LOGOUT_FAIL',
}

export { USER };